---
title: "Historical visualizations"
author: "Elias M Guerra"
date: "3/24/2018"
output: github_document
---

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(stringr)
library(tidyverse)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
## World Population data
# http://www.ggdc.net/maddison/oriindex.htm
setwd("~/Documents/R/just_for_fun/maddison_worldpopulation-gdp-percapita/")
list.files()
maddison_pop <- read.csv("Population-Table 1.csv", skip = 2, header = T, stringsAsFactors = F)
maddison_pop <- maddison_pop[!is.na(maddison_pop$X),]
colnames(maddison_pop)[1] <- "year"
poplong <- gather(maddison_pop, country, population, -year) # make data long
poplong$country <- tolower(poplong$country)
poplong$population <- poplong$population %>% str_replace_all(",","") %>% as.numeric()
poplong$population <- poplong$population/1000
# Additional population data copied from textbook "Europe 1783-1914" by William Simpson and Martin Jones (3rd Ed)
simpsonjones_population <- read_csv("~/Documents/R/just_for_fun/population_europe_simpsonandjones2015.csv")
simpsonjones_population <- simpsonjones_population[1:10,1:4]
simpsonjones_population$country[1:2] <- c("uk","austria")
simpsonjones_population$country <- tolower(simpsonjones_population$country)
simpsonjones_population <- gather(simpsonjones_population, year, population, -country) %>% arrange()
simpsonjones_population <- simpsonjones_population[c("year","country","population")]
simpsonjones_population <- filter(simpsonjones_population, year != 1850)
# Combine datasets
poplong <- rbind(simpsonjones_population, poplong) 
poplong$year <- as.numeric(poplong$year)
# Graph: Population in Western Europe, 1700 to present
poplong %>% 
  filter(year >= 1700, country %in% c("uk","germany","france", "italy")) %>% 
  ggplot + 
  geom_line(aes(year, population, color = country, linetype = country)) +
  ggtitle("Population in Western Europe, 1700 to present") +
  ylab("population (millions)") +
  geom_text(data = data.frame(
    x = c(1965, 1910, 1915, 1915 ),
    y = c(42, 68, 35, 49),
    text = c("France", "Germany", "Italy","United Kingdom")
  ), aes(x,y,label = text)) +
  guides(color = F, linetype = F)
```

#### References


